info:
  namespace: greek_talismans

items:
  talisman_fugu:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Фуги"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+6 Урон"
      - "&c-2 Макс. здоровье"
      - "&c-4 Твёрдость брони"
      - "&c-4 Броня"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 6
        maxHealth: -2
        armorToughness: -4
        armor: -4

  talisman_egida:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Эгида"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+2 Броня"
      - "&9+2 Твёрдость брони"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        armor: 2
        armorToughness: 2

  talisman_karatelya:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Карателя"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+7 Урон"
      - "&9+10% Скорость ходьбы"
      - "&c-4 Макс. здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 7
        movementSpeed: 0.010
        maxHealth: -4

  talisman_kraita:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Крайта"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+4 Урон"
      - "&9+2 Броня"
      - "&9+2 Твёрдость брони"
      - "&c-25% Скорость атаки"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 4
        armor: 2
        armorToughness: 2
        attackSpeed: -0.025

  talisman_kobry:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Кобры"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+5 Урон"
      - "&c-4 Макс. здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 5
        maxHealth: -4

  talisman_manesa:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Манеса"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+30% Скорость атаки"
      - "&c-2 Урон"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackSpeed: 0.030
        attackDamage: -2

  talisman_lekarya:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Лекаря"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+6 Макс. здоровье"
      - "&c-4 Броня"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        maxHealth: 6
        armor: -4

  talisman_dionisa:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Диониса"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+2 Урон"
      - "&9+15% Скорость атаки"
      - "&9+10% Скорость ходьбы"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 2
        attackSpeed: 0.015
        movementSpeed: 0.010

  talisman_gefesta:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Гефеста"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Урон"
      - "&9+2 Макс. здоровье"
      - "&9+20% Скорость атаки"
      - "&c-50% Скорость ходьбы"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 3
        maxHealth: 2
        attackSpeed: 0.02
        movementSpeed: -0.05

  talisman_khauberka:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Хауберка"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+5 Урон"
      - "&c-15% Скорость ходьбы"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 5
        movementSpeed: -0.015

  talisman_krushitelya:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Крушителя"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Урон"
      - "&9+4 Макс. здоровье"
      - "&9+2 Броня"
      - "&9+2 Твёрдость брони"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 3
        maxHealth: 4
        armor: 2
        armorToughness: 2

  talisman_grani:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Грани"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+15 Скорость ходьбы"
      - "&9+3 Урон"
      - "&c-4 Макс. здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        movementSpeed: 0.015
        attackDamage: 3
        maxHealth: -4

  talisman_dedala:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Дедала"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+5 Урон"
      - "&c-4 Макс. здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 5
        maxHealth: -4

  talisman_tritona:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Тритона"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Защиты"
      - "&9+2 Макс. здоровье"
      - "&c-3 Твёрдость брони"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        armor: 3
        maxHealth: 2
        armorToughness: -3

  talisman_garmonii:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Гармонии"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+2 Урон"
      - "&9+2 Макс. здоровье"
      - "&9+2 Защиты"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 2
        maxHealth: 2
        armor: 2

  talisman_feniksa:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Феникса"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+6 Макс. здоровье"
      - "&9+10% Скорость атаки"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        maxHealth: 6
        attackSpeed: 0.010

  talisman_ekhidny:
    enabled: true
    display_name: "&#f0f034Ξ &fТалисман Ехидны"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+6 Урон"
      - "&c-2 Защиты"
      - "&c-2 Твёрдость брони"
      - "&c-4 Макс. здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: TOTEM_OF_UNDYING
      generate: false
      model_path: item/talisman_totem
    attribute_modifiers:
      offhand:
        attackDamage: 6
        armor: -2
        armorToughness: -2
        maxHealth: -4

  # ---------- СФЕРЫ (3D-модели, ItemsAdder) ----------

  iaso:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Иасо"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+1 Твердость брони"
      - "&9+1 Броня"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_iaso.json"
    attribute_modifiers:
      offhand:
        armorToughness: 1
        armor: 1

  skifa:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Скифа"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+10% Скорость атаки"
      - "&9+10% Скорость ходьбы"
      - "&c-2 Броня"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_skifa.json"
    attribute_modifiers:
      offhand:
        attackSpeed: 0.01
        movementSpeed: 0.01
        armor: -2

  abanta:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Абанты"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+2 Максимальное здоровье"
      - "&9+1 Везение"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_abanta.json"
    attribute_modifiers:
      offhand:
        maxHealth: 2
        luck: 1

  filona:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Филона"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+20% Скорость атаки"
      - "&9+2 Максимальное здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_filona.json"
    attribute_modifiers:
      offhand:
        attackSpeed: 0.02
        maxHealth: 2

  sorana:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Сорана"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Урон"
      - "&9+2 Максимальное здоровье"
      - "&c-3 Броня"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_sorana.json"
    attribute_modifiers:
      offhand:
        attackDamage: 3
        maxHealth: 2
        armor: -3

  epion:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Эпиона"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Урон"
      - "&c-2 Максимальное здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_epion.json"
    attribute_modifiers:
      offhand:
        attackDamage: 3
        maxHealth: -2

  afina:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Афина"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+15% Скорость ходьбы"
      - "&9+15% Скорость атаки"
      - "&9+3 Урон"
      - "&c-2 Максимальное здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_afina.json"
    attribute_modifiers:
      offhand:
        movementSpeed: 0.015
        attackSpeed: 0.015
        attackDamage: 3
        maxHealth: -2

  panakea:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Панакея"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+4 Урон"
      - "&c-2 Максимальное здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_panakea.json"
    attribute_modifiers:
      offhand:
        attackDamage: 4
        maxHealth: -2

  magma:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Магмы"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+2 Броня"
      - "&9+2 Твердость брони"
      - "&c-15% Скорость ходьбы"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_magma.json"
    attribute_modifiers:
      offhand:
        armor: 2
        armorToughness: 2
        movementSpeed: -0.015

  teurgia:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Теургия"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+4 Урон"
      - "&9+4 Максимальное здоровье"
      - "&c-15% Скорость атаки"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_teurgia.json"
    attribute_modifiers:
      offhand:
        attackDamage: 4
        maxHealth: 4
        attackSpeed: -0.015

  andromeda:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Андромеды"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+15% Скорость ходьбы"
      - "&9+2 Защиты"
      - "&9+3 Урона"
      - "&c-4 Максимальное здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_andromeda.json"
    attribute_modifiers:
      offhand:
        movementSpeed: 0.015
        armor: 2
        attackDamage: 3
        maxHealth: -4

  pandora:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Пандоры"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+25% Урон"
      - "&9+10% Скорость ходьбы"
      - "&c-10% Защиты"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_pandora.json"
    attribute_modifiers:
      offhand:
        attackDamage: 5
        movementSpeed: 0.010
        armor: -2

  titan:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Титана"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Броня"
      - "&9+3 Твёрдости брони"
      - "&c-15% Скорость ходьбы"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_titan.json"
    attribute_modifiers:
      offhand:
        armor: 3
        armorToughness: 3
        movementSpeed: -0.015

  apollon:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Аполлона"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+4 Урон"
      - "&c-10% Скорость ходьбы"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_apollon.json"
    attribute_modifiers:
      offhand:
        attackDamage: 4
        movementSpeed: -0.010

  astreya:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Астрея"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+4 Максимальное здоровье"
      - "&9+3 Урон"
      - "&c-15% Скорость атаки"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_astreya.json"
    attribute_modifiers:
      offhand:
        maxHealth: 4
        attackDamage: 3
        attackSpeed: -0.015

  osiris:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Осириса"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Защиты"
      - "&9+15% Отдача"
      - "&c-15% Защиты отдачи"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_osiris.json"
    attribute_modifiers:
      offhand:
        armor: 3
        armorToughness: 1
        knockbackResistance: -0.015

  chimera:
    enabled: true
    display_name: "&#f0f034Ξ &fСфера Химеры"
    lore:
      - ""
      - "&7Когда во второстпеной руке:"
      - "&9+3 Урон"
      - "&9+15% Скорость атаки"
      - "&c-2 Максимальное здоровье"
    glint: true
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      material: PLAYER_HEAD
      generate: false
      model_path: "minecraft:item/player_head"
    components_nbt_file: "sphere_chimera.json"
    attribute_modifiers:
      offhand:
        attackDamage: 3
        attackSpeed: 0.015
        maxHealth: -2
